services:
  api-gateway:
    container_name: api-gateway
    build: ./backend/api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./backend/api-gateway/.env
    volumes:
      - ./backend/api-gateway:/app
    command: npm run dev
    depends_on:
      - user-service
      - item-service
      - reminder-service
      - notification-service
      - recipe-service

  user-service:
    container_name: user-service
    build: ./backend/user-service
    ports:
      - "4001:4001"
    env_file:
      - ./backend/user-service/.env
    volumes:
      - ./backend/user-service:/app
    command: npm run dev

  item-service:
    container_name: item-service
    build: ./backend/item-service
    ports:
      - "4002:4002"
    env_file:
      - ./backend/item-service/.env
    volumes:
      - ./backend/item-service:/app
    command: npm run dev

  item-service-worker:
    container_name: item-service-worker
    build: ./backend/item-service
    volumes:
      - ./backend/item-service:/app
    command: node src/worker.js

  reminder-service:
    container_name: reminder-service
    build: ./backend/reminder-service
    ports:
      - "4003:4003"
    env_file:
      - ./backend/reminder-service/.env
    volumes:
      - ./backend/reminder-service:/app
    command: npm run dev

  reminder-service-worker:
    container_name: reminder-service-worker
    build: ./backend/reminder-service
    volumes:
      - ./backend/reminder-service:/app
    command: node src/worker.js

  notification-service:
    container_name: notification-service
    build: ./backend/notification-service
    ports:
      - "4004:4004"
    env_file:
      - ./backend/notification-service/.env
    volumes:
      - ./backend/notification-service:/app
    command: npm run dev

  recipe-service:
    container_name: recipe-service
    build: ./backend/recipe-service
    ports:
      - "4005:4005"
    env_file:
      - ./backend/recipe-service/.env
    volumes:
      - ./backend/recipe-service:/app
    command: npm run dev

  react-app:
    container_name: react-app
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
